name: Test and release with pytest and gh
on:
  push:
    branches: ["**"]
  schedule:
    - cron: 0 10 * * 6 # every Saturday at 10 AM
  workflow_dispatch:
jobs:
  test_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Build grammar library
        run: python3 scripts/build_library.py
      - name: Test with pytest
        run: pytest
      - name: Release with gh
        run: ./scripts/release.sh
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_TOKEN: ${{ github.token }}
