name: Test and release with pytest and gh
on:
  push:
    branches: ["**"]
  schedule:
    - cron: 0 10 * * 6 # every Saturday at 10 AM
  workflow_dispatch:
jobs:
  test_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch submodules
        run: |
          git submodule init
          git submodule update
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Test with pytest
        run: |
          pytest
      - name: Release with gh
        run: ./scripts/release.sh
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_TOKEN: ${{ github.token }}
